AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ProjectName: { Type: String }
  Environment: { Type: String }
  VPCId: { Type: String }
  SGWeb: { Type: String }
  SubnetId: { Type: String }
  DBHost: { Type: String }

Resources:
  # ロググループの作成
  ECSLogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Sub "/ecs/${ProjectName}-${Environment}-log"
      RetentionInDays: 7

  # 実行ロール
  ECSTaskExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "ecs-tasks.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"

  # タスクロール
  ECSTaskRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "ecs-tasks.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: !Sub "${ProjectName}-${Environment}-task-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "ssmmessages:CreateControlChannel"
                  - "ssmmessages:CreateDataChannel"
                  - "ssmmessages:OpenControlChannel"
                  - "ssmmessages:OpenDataChannel"
                Resource: "*"

  ECSCluster:
    Type: "AWS::ECS::Cluster"
    Properties:
      ClusterName: !Sub "${ProjectName}-${Environment}-cluster"

  ECSTaskDefinition:
    Type: "AWS::ECS::TaskDefinition"
    Properties:
      Family: !Sub "${ProjectName}-${Environment}-task"
      Cpu: "256"
      Memory: "512"
      NetworkMode: "awsvpc"
      RequiresCompatibilities:
        - "FARGATE"
      ExecutionRoleArn: !GetAtt ECSTaskExecutionRole.Arn
      TaskRoleArn: !GetAtt ECSTaskRole.Arn
      ContainerDefinitions:
        - Name: "app"
          Image: !Sub "${AWS::AccountId}.dkr.ecr.ap-northeast-1.amazonaws.com/laraec-app:latest"
          PortMappings:
            - ContainerPort: 80
          # ログ出力の設定を追加
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref ECSLogGroup
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: ecs
          Environment:
            - Name: "DB_HOST"
              Value: !Ref DBHost
            - Name: "DB_DATABASE"
              Value: "laraec"
            - Name: "DB_USERNAME"
              Value: "admin"
            - Name: "DB_PASSWORD"
              Value: "password123"

  ECSService:
    Type: "AWS::ECS::Service"
    Properties:
      EnableExecuteCommand: true
      Cluster: !Ref ECSCluster
      ServiceName: !Sub "${ProjectName}-${Environment}-service"
      TaskDefinition: !Ref ECSTaskDefinition
      LaunchType: "FARGATE"
      DesiredCount: 1
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: "ENABLED"
          SecurityGroups:
            - !Ref SGWeb
          Subnets:
            - !Ref SubnetId

Outputs:
  ECSClusterName:
    Value: !Ref ECSCluster

  ECSServiceName:
    Value: !GetAtt ECSService.Name
